archive file path updated !

diff --git a/.github/workflows/pullRequest.yml b/.github/workflows/pullRequest.yml
--- a/.github/workflows/pullRequest.yml
+++ b/.github/workflows/pullRequest.yml
@@ -35,13 +35,30 @@ jobs:
       - name: Archive the App
         run: |
           xcodebuild archive -project TestPipelines.xcodeproj \
-            -scheme TestPipelines \
+            xcodebuild -scheme TestPipelines \
             -configuration Release \
-            -archivePath ${{ github.workspace }}/TestPipelines.xcarchive \
+            -archivePath /Users/runner/Library/Developer/Xcode/Archives/TestPipelines.xcarchive archive
             -destination 'generic/platform=iOS Simulator' archive
-      - name: Move archive to repo root
+
+      - name: Verify archive path
         run: |
-            mv "/Users/runner/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')/TestPipelines.xcarchive" "$GITHUB_WORKSPACE/"
+              if [ -d "/Users/runner/Library/Developer/Xcode/Archives/TestPipelines.xcarchive" ]; then
+                echo "Archive found!"
+              else
+                echo "Archive not found at expected location."
+                exit 1
+              fi
+
+    #   - name: Move archive to repo root
+    #      if: success() # Only run if the previous step succeeded
+    # run: |
+    #   mv "/Users/runner/Library/Developer/Xcode/Archives/TestPipelines.xcarchive" "$GITHUB_WORKSPACE/"
+  
+
+
+
+
+
     #   - name: Export IPA
     #     run: |
     #       xcodebuild -exportArchive \
